### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by idleberg**
It's been my experience that using [EditorConfig](http://editorconfig.org/) is a good idea when there are many contributors, just to make sure we follow the same set of rules without the need to meddle with one's personal editor preferences.

### CODE REVIEW

**Comment by grandchild** [comment]
Isn't forcing `end_of_line = lf` a bit harsh on windows? Don't know how this would work out on windows. In my experience it's best to leave git's `autocrlf` on or default, and not force line-endings too much.

**Comment by idleberg** [comment]
Any Windows users who want to comment on @grandchild's remark? Note that I've since made some modifications.

**Comment by grandchild** [comment]
Um, I wouldn't want to have crlf either. I think that we don't need to specify line-endings. Git will take care of that.

**Comment by idleberg** [comment]
> I think that we don't need to specify line-endings. Git will take care of that.

Personally I don't care about the actual line-endings used, but I disagree with the above statement.

EditorConfig is meant to find a common ground between developers and as such should have higher priority over any user preference, whether it's your text-editor, version control or any other tool involved. You must always assume that there's a potential contributor that has reason to use a different, even awkward `core.autocrlf` setting.

**Comment by idleberg** [comment]
TODO: test against [eclint](https://www.npmjs.com/package/eclint)

**Comment by grandchild** [comment]
Okay, then I'd vote for LF, but that's obviously biased. Also, yeah, I don't care that much either.
My initial comment was just meant as a cautonary remark, that azeem might be inconvenienced by this. I don't think anything will really break.

**Comment by grandchild** [comment]
also, bikeshedding ;)

**Comment by tbeckenhauer** [comment]
Perhaps we can handle the LF issues by testing it with a CI/CD process?

**Comment by idleberg** [comment]
> Perhaps we can handle the LF issues by testing it with a CI/CD process?

I'm currently looking into [eclint](https://www.npmjs.com/package/eclint), since it can test your code against `.editorconfig`. However, at this state we should probably stay away, since GitHub reports it to have vulnerable dependencies.

**Comment by azeem** [comment]
I personally switch between windows and linux for dev so i don't have a preference for `lf` or `crlf`. But I'm not convinced that we need a `.editorconfig`. We should have consistent line ending for all files in the project whether it's `lf` or `crlf`. But a `.gitattribute` setting should be enough for this https://help.github.com/articles/dealing-with-line-endings/.

As for enforcing indentation, trailing whitespace etc. the existing [tslint config](https://github.com/azeem/webvs/blob/master/tslint.json) should suffice. Please feel free to add to that if the defaults are not reasonable.

We could add `node lint` to CI pipeline when we have one. The func-tests maybe a bit flaky but it was running fine on Chrome/Linux for me. They're always gonna be a bit flaky because no two webgl implementation will render things exactly the same. We could adjust image comparison thresholds to make it less flaky.

**Comment by idleberg** [comment]
> We could add node lint to CI pipeline when we have one.

For most of my life on GitHub, I've been using Travis CI. However, lately I found out that Circle CI is so much faster for doing the same thing: setup a node environment,`npm install`, `npm test`

**Comment by idleberg** [comment]
> As for enforcing indentation, trailing whitespace etc. the existing tslint config should suffice. Please feel free to add to that if the defaults are not reasonable.

As far as I can tell, there is one significant difference. A linter notifies about mismatching coding styles, while EditorConfig applies them without further action. 

`tslint` has support to fix very basic things:

> Rules that support the `--fix` feature:
>
> `array-type`
> `arrow-parens`
> `no-unused-variable` (for imports)
> `no-var-keyword`
> `ordered-imports`
> `semicolon`
> `trailing-comma`

Even if you (or any other potential contributor) don't use EditorConfig, it's a great benefit for those who do.

**Pull request merged**
